services:
  flask_app:
    build: ./other
    ports:
      - "5000:5000"

  react-app:
    container_name: react-app
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true

  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYsqldocker1Pass2
      MYSQL_DATABASE: dockerusers2-mysql
      MYSQL_USER: dockerusers2-user
      MYSQL_PASSWORD: MYsqldocker1Pass2
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: