FROM node:16
WORKDIR /app
ENV CI=true
COPY package.json ./
RUN npm install
COPY . .

FROM python:3-alpine
WORKDIR /app
RUN apk add --no-cache mariadb-dev gcc musl-dev
COPY other/requirements.txt .
RUN pip install -r requirements.txt
COPY . .

EXPOSE 3000
CMD ["npm", "start"]